name: "Action compare branchs on Pull-request"
description: "Get started with Python Container actions"
author: "Rafael Dalsenter"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
